### ISSUE TITLE
Implement new Database option.

### ISSUE THREAD

**Issue by mattlol85** [mattlol85/FitzNet-Hardcore#7]
The database is currently running on a janky .txt file in which I am not particularly proud of.

There are several options I would find acceptable such as...

1.  MongoDB
2. MariaDB
3. JSON Files for each player
4. PLAYERUUID.yml files in a separate directory.

**Comment by kenny-designs** [comment]
I'll take the case! Working on JSON now.

**Comment by mattlol85** [comment]
Switching to YML files for easier server administration.

**Comment by mattlol85** [comment]
Now using YML. Closing.
